server:
    port: 8443
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/white_jotter?characterEncoding=UTF-8&useSSL=false
        username: root
        password: majie1112
        driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
mapper-locations: classpath:mapper/*.xml

typeAliasesPackage: com.evan.wj.pojo
global-config:

id-type: 0

field-strategy: 2

db-column-underline: true

refresh-mapper: true

logic-delete-value: -1
logic-not-delete-value: 0

configuration:
map-underscore-to-camel-case: true
cache-enabled: false
call-setters-on-nulls: true

